INSERT INTO products (name, description, price, stock) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI.', 450.00, 50),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard with tactile switches.', 2300.00, 50),
('USB-C Charger', 'Fast charging USB-C charger for phones and tablets.', 550.00, 50),
('Bluetooth Earbuds', 'True wireless earbuds with noise cancellation.', 1200.00, 50),
('Portable SSD 500GB', 'High-speed external SSD for storage on the go.', 3200.00, 50),
('Laptop Stand', 'Adjustable aluminum laptop stand for better posture.', 850.00, 50),
('Gaming Headset', 'Surround sound gaming headset with microphone.', 1500.00, 50),
('Smartwatch', 'Waterproof smartwatch with fitness tracking.', 2000.00, 50),
('Wireless Keyboard', 'Slim wireless keyboard compatible with multiple devices.', 1000.00, 50),
('HD Webcam', '1080p webcam with built-in microphone.', 1800.00, 50),
('LED Desk Lamp', 'Adjustable LED desk lamp with brightness levels.', 750.00, 50),
('Power Bank 10,000mAh', 'Compact power bank for charging devices on the go.', 950.00, 50),
('Laptop Backpack', 'Water-resistant backpack with laptop compartment.', 1200.00, 50),
('HDMI Cable 2m', 'High-speed HDMI cable for HD video and audio.', 350.00, 50),
('Gaming Mouse Pad', 'Extra-large mouse pad for gaming or office use.', 400.00, 50),
('Noise Cancelling Headphones', 'Over-ear headphones with active noise cancellation.', 3500.00, 50),
('Tablet Stand', 'Adjustable stand for tablets and e-readers.', 500.00, 50),
('USB Hub 4-Port', 'Expand a single USB port into four with this hub.', 600.00, 50),
('Smart Light Bulb', 'Wi-Fi enabled LED light bulb with color options.', 750.00, 50),
('External DVD Drive', 'Portable USB DVD/CD drive for laptops.', 1100.00, 50);
